version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crypto-stock-portfolio-backend"
s3_prefix = "crypto-stock-portfolio-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "JWTSecret=\"your-secret-key-here\" CoinGeckoAPIKey=\"\""

[default.build]
[default.build.parameters]
cached = true
parallel = true
